name: Build MiladGeo Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Windows
        run: npm run make

      - name: Prepare installer
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path release

          $installer = Get-ChildItem `
            -Path "out\make" `
            -Filter "*Setup.exe" `
            -Recurse |
            Select-Object -First 1

          if (-not $installer) {
            Write-Error "MiladGeo installer was not found."
            exit 1
          }

          Copy-Item `
            $installer.FullName `
            "release\MiladGeo-Setup.exe"

          Write-Host "Installer found:"
          Write-Host $installer.FullName

      - name: Upload installer only
        uses: actions/upload-artifact@v4
        with:
          name: MiladGeo-Windows-Installer
          path: release/MiladGeo-Setup.exe
          if-no-files-found: error
